import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const INDIGO: [number, number, number] = [79, 70, 229];
const EMERALD: [number, number, number] = [16, 185, 129];
const SLATE: [number, number, number] = [51, 65, 85];
const LIGHT: [number, number, number] = [226, 232, 240];
const DARK: [number, number, number] = [30, 41, 59];
const MUTED: [number, number, number] = [71, 85, 105];
const AMBER: [number, number, number] = [217, 119, 6];

function sectionHeader(doc: jsPDF, title: string, y: number): number {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(title, 15, y);
    doc.setDrawColor(...LIGHT);
    doc.setLineWidth(0.4);
    doc.line(15, y + 2, 195, y + 2);
    return y + 12;
}

function needsPage(doc: jsPDF, y: number, needed = 50): number {
    if (y + needed > 270) {
        doc.addPage();
        return 20;
    }
    return y;
}

export const generateHiringReport = async (data: { collection: any; candidates: any[] }) => {
    const { collection, candidates } = data;
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

    // ── Cover ─────────────────────────────────────────────────────────────────
    doc.setFillColor(18, 18, 21);
    doc.rect(0, 0, 210, 60, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("HIRING INTELLIGENCE REPORT", 105, 22, { align: "center" });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(180, 180, 200);
    doc.text(`Generated by ChainVolio  •  ${dateStr}`, 105, 31, { align: "center" });

    doc.setDrawColor(...INDIGO);
    doc.setLineWidth(1.2);
    doc.line(70, 36, 140, 36);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.text(`Collection: ${collection.title}`, 105, 47, { align: "center" });
    doc.setFontSize(9);
    doc.setTextColor(160, 160, 180);
    doc.text(`Role: ${collection.metadata?.roleType || "Not Specified"}`, 105, 55, { align: "center" });

    // ── Section 1: Executive Summary ─────────────────────────────────────────
    let y = 76;
    y = sectionHeader(doc, "1. EXECUTIVE SUMMARY", y);

    const verifiedCount = candidates.filter(c => c.isVerified).length;
    const avgScoreValue = candidates.reduce((acc, c) => acc + (c.signalScore || 0), 0) / (candidates.length || 1);
    const avgScore = avgScoreValue.toFixed(1);
    const avgYoe = (candidates.reduce((acc, c) => acc + (c.yearsOfExperience || 0), 0) / (candidates.length || 1)).toFixed(1);
    const signalDensity = (candidates.reduce((acc, c) => acc + (c.powCount || 0), 0) / (candidates.length || 1)).toFixed(1);
    const networkBreadth = new Set(candidates.flatMap(c => c.attestedOrgs)).size;
    const authorityRateValue = candidates.length ? ((candidates.filter(c => c.attestedCount > 0).length / candidates.length) * 100) : 0;
    const authorityRate = authorityRateValue.toFixed(0);
    const totalAttested = candidates.reduce((acc, c) => acc + (c.attestedCount || 0), 0);
    const totalProofs = candidates.reduce((acc, c) => acc + (c.powCount || 0), 0);

    const statsData = [
        ["Total Applicants", candidates.length.toString(), "Avg. Signal Score", `${avgScore} / 100`],
        ["Verified Candidates", verifiedCount.toString(), "Avg. Years Experience", `${avgYoe} yrs`],
        ["Authority Rate", `${authorityRate}%`, "Total Proof Records", totalProofs.toString()],
        ["Total Attestations", totalAttested.toString(), "Network Breadth", `${networkBreadth} partner orgs`],
        ["Signal Density", `${signalDensity} avg. proofs`, "Shortlist Ready", `${candidates.filter(c => (c.signalScore || 0) >= 70 && c.isVerified).length} candidates`],
    ];

    autoTable(doc, {
        startY: y,
        body: statsData,
        theme: "grid",
        styles: { fontSize: 9, cellPadding: 2.5 },
        columnStyles: {
            0: { fontStyle: "bold", cellWidth: 50, fillColor: [245, 247, 250] },
            1: { cellWidth: 35 },
            2: { fontStyle: "bold", cellWidth: 50, fillColor: [245, 247, 250] },
            3: { cellWidth: 35 },
        },
        margin: { left: 15, right: 15 },
    });

    y = (doc as any).lastAutoTable.finalY + 8;

    // Insight callouts
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...MUTED);
    const insights: string[] = [];
    if (verifiedCount === candidates.length && candidates.length > 0)
        insights.push("All candidates are verified — this is an exceptionally strong applicant pool.");
    else if (verifiedCount > 0)
        insights.push(`${verifiedCount} of ${candidates.length} candidates hold verified status, providing a solid trust baseline.`);
    if (avgScoreValue > 60)
        insights.push("Signal strength is above average with strong on-chain proof density.");
    if (authorityRateValue > 50)
        insights.push(`${authorityRate}% of candidates have at least one third-party attested proof record.`);
    if (parseFloat(avgYoe) >= 3)
        insights.push(`Candidates average ${avgYoe} years of professional experience — a senior-leaning pool.`);

    insights.forEach(insight => {
        y = needsPage(doc, y, 8);
        doc.text(`• ${insight}`, 17, y);
        y += 6;
    });

    // ── Section 2: Shortlist / Smart Recommendations ─────────────────────────
    y = needsPage(doc, y, 60);
    y += 6;
    y = sectionHeader(doc, "2. SHORTLIST — TOP CANDIDATES", y);

    const sortedCandidates = [...candidates].sort((a, b) => (b.signalScore || 0) - (a.signalScore || 0));
    const topCandidates = sortedCandidates.slice(0, 5);

    const shortlistData = topCandidates.map((c, i) => {
        let decision = "Technical Screening";
        if (c.signalScore >= 75 && c.isVerified) decision = "Proceed to Interview";
        else if (c.signalScore < 30) decision = "Monitor";
        else if (c.isVerified) decision = "Proceed to Interview";
        else if (c.powCount > 8) decision = "Technical Screening";

        const yoeStr = c.yearsOfExperience > 0 ? `${c.yearsOfExperience} yrs` : "—";
        const proofStr = `${c.attestedCount}/${c.powCount}`;

        return [
            (i + 1).toString(),
            c.displayName || c.wallet.slice(0, 10) + "…",
            yoeStr,
            c.verificationTier !== "unverified" ? c.verificationTier : "None",
            `${c.signalScore}/100`,
            proofStr,
            decision,
        ];
    });

    autoTable(doc, {
        startY: y,
        head: [["#", "Candidate", "YOE", "Tier", "Score", "Att./Total", "Recommendation"]],
        body: shortlistData,
        theme: "striped",
        headStyles: { fillColor: EMERALD, fontSize: 8 },
        styles: { fontSize: 8, cellPadding: 2.5 },
        columnStyles: {
            0: { cellWidth: 8 },
            1: { cellWidth: 45 },
            2: { cellWidth: 16 },
            3: { cellWidth: 30 },
            4: { cellWidth: 18 },
            5: { cellWidth: 20 },
            6: { fontStyle: "bold", cellWidth: 30 },
        },
        didParseCell: (data) => {
            if (data.section === "body" && data.column.index === 6) {
                const val = data.cell.raw as string;
                if (val === "Proceed to Interview") data.cell.styles.textColor = EMERALD;
                else if (val === "Monitor") data.cell.styles.textColor = MUTED;
                else data.cell.styles.textColor = AMBER;
            }
        },
        margin: { left: 15, right: 15 },
    });

    // ── Section 3: Full Candidate Breakdown ───────────────────────────────────
    y = (doc as any).lastAutoTable.finalY + 15;
    y = needsPage(doc, y, 60);
    y = sectionHeader(doc, "3. FULL CANDIDATE BREAKDOWN", y);

    const breakdownData = sortedCandidates.map(c => {
        const ratio = c.powCount > 0 ? `${((c.attestedCount / c.powCount) * 100).toFixed(0)}%` : "0%";
        const yoeStr = c.yearsOfExperience > 0 ? `${c.yearsOfExperience}` : "—";
        return [
            c.displayName || "Anonymous",
            yoeStr,
            `${c.signalScore}/100`,
            c.verificationTier !== "unverified" ? c.verificationTier : "None",
            c.powCount.toString(),
            c.attestedCount.toString(),
            ratio,
            c.recruiterStatus || "Applied",
        ];
    });

    autoTable(doc, {
        startY: y,
        head: [["Name", "YOE", "Score", "Tier", "Proofs", "Att.", "Ratio", "Status"]],
        body: breakdownData,
        theme: "grid",
        headStyles: { fillColor: SLATE, fontSize: 8 },
        styles: { fontSize: 7.5, cellPadding: 2 },
        columnStyles: {
            0: { fontStyle: "bold", cellWidth: 42 },
            1: { cellWidth: 14 },
            2: { cellWidth: 20 },
            3: { cellWidth: 32 },
            4: { cellWidth: 16 },
            5: { cellWidth: 12 },
            6: { cellWidth: 16 },
            7: { cellWidth: 25 },
        },
        didParseCell: (data) => {
            if (data.section === "body" && data.column.index === 2) {
                const score = parseInt((data.cell.raw as string).split("/")[0]);
                if (score >= 70) data.cell.styles.textColor = EMERALD;
                else if (score >= 30) data.cell.styles.textColor = AMBER;
                else data.cell.styles.textColor = [180, 60, 60];
            }
        },
        margin: { left: 15, right: 15 },
    });

    // ── Section 4: Signal Analysis ────────────────────────────────────────────
    y = (doc as any).lastAutoTable.finalY + 15;
    y = needsPage(doc, y, 50);
    y = sectionHeader(doc, "4. SIGNAL ANALYSIS", y);

    const highConfidenceCount = candidates.filter(c => (c.signalScore || 0) >= 70).length;
    const avgAttestRatio = candidates.length
        ? (candidates.reduce((acc, c) => acc + (c.powCount > 0 ? c.attestedCount / c.powCount : 0), 0) / candidates.length * 100).toFixed(1)
        : "0.0";
    const topPerformer = sortedCandidates[0];
    const mostExperienced = [...candidates].sort((a, b) => (b.yearsOfExperience || 0) - (a.yearsOfExperience || 0))[0];

    autoTable(doc, {
        startY: y,
        body: [
            ["High Confidence Candidates (Score ≥ 70)", highConfidenceCount.toString()],
            ["Avg. Attestation Ratio", `${avgAttestRatio}%`],
            ["Top Signal Scorer", `${topPerformer?.displayName || topPerformer?.wallet?.slice(0, 10) || "None"} — ${topPerformer?.signalScore || 0}/100`],
            ["Most Experienced Candidate", `${mostExperienced?.displayName || mostExperienced?.wallet?.slice(0, 10) || "None"} — ${mostExperienced?.yearsOfExperience || 0} yrs`],
            ["Most Attested Proofs", `${sortedCandidates[0]?.displayName || "None"} — ${sortedCandidates[0]?.attestedCount || 0} attested records`],
        ],
        theme: "plain",
        styles: { fontSize: 9, cellPadding: 2.5 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 90 } },
        margin: { left: 15, right: 15 },
    });

    // ── Section 5: Internal Process Log ──────────────────────────────────────
    y = (doc as any).lastAutoTable.finalY + 15;
    y = needsPage(doc, y, 50);
    y = sectionHeader(doc, "5. INTERNAL PROCESS LOG", y);

    autoTable(doc, {
        startY: y,
        head: [["Wallet Ref", "Internal Status", "Recruiter Notes", "Submission Date"]],
        body: sortedCandidates.map(c => [
            c.wallet.slice(0, 8) + "…",
            c.recruiterStatus || "Applied",
            c.recruiterNotes || "—",
            new Date(c.submittedAt).toLocaleDateString(),
        ]),
        theme: "plain",
        styles: { fontSize: 7.5, cellPadding: 1.5 },
        columnStyles: { 2: { cellWidth: 65 } },
        margin: { left: 15, right: 15 },
    });

    // ── Section 6: Detailed Candidate Profiles ────────────────────────────────
    doc.addPage();
    y = 20;
    y = sectionHeader(doc, "6. DETAILED CANDIDATE PROFILES", y);

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...MUTED);
    doc.text(
        "Each profile includes verified proof-of-work records captured at application time, attestation status, and years of experience.",
        15, y
    );
    y += 10;

    sortedCandidates.forEach((c, idx) => {
        y = needsPage(doc, y, 60);

        // ── Candidate header bar ──
        doc.setFillColor(240, 242, 248);
        doc.roundedRect(14, y - 4, 181, 14, 2, 2, "F");

        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...DARK);
        const nameStr = `${idx + 1}. ${c.displayName || c.wallet.slice(0, 10) + "…"}`;
        doc.text(nameStr, 17, y + 5);

        // Score badge on the right
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        const scoreColor: [number, number, number] =
            c.signalScore >= 70 ? EMERALD : c.signalScore >= 30 ? AMBER : [180, 60, 60];
        doc.setTextColor(...scoreColor);
        doc.text(`Score: ${c.signalScore}/100`, 185, y + 5, { align: "right" });

        y += 16;

        // ── Meta row ──
        doc.setFontSize(8.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...MUTED);

        const yoeLabel = c.yearsOfExperience > 0 ? `${c.yearsOfExperience} yrs experience` : "Experience: unknown";
        const tierLabel = c.verificationTier !== "unverified" ? `Tier: ${c.verificationTier}` : "Unverified";
        const verLabel = c.isVerified ? "✓ Verified" : "Not verified";
        const proofLabel = `${c.powCount} proofs (${c.attestedCount} attested)`;

        doc.text(`${yoeLabel}  |  ${tierLabel}  |  ${verLabel}  |  ${proofLabel}`, 15, y);
        y += 5;

        doc.setFontSize(7.5);
        doc.setTextColor(140, 140, 160);
        doc.text(`Wallet: ${c.wallet}`, 15, y);
        y += 6;

        // ── Primary signal & role ──
        if (c.primarySignal || c.role) {
            doc.setFontSize(8.5);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...MUTED);
            const roleStr = [c.role, c.primarySignal].filter(Boolean).join("  ·  ");
            doc.text(roleStr.length > 100 ? roleStr.substring(0, 97) + "…" : roleStr, 15, y);
            y += 6;
        }

        // ── Bio ──
        if (c.snapshotBio) {
            y = needsPage(doc, y, 18);
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...DARK);
            doc.text("Bio", 15, y);
            y += 4;
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...MUTED);
            const bioLines = doc.splitTextToSize(c.snapshotBio, 175);
            const maxLines = Math.min(bioLines.length, 4);
            doc.text(bioLines.slice(0, maxLines), 15, y);
            y += maxLines * 4.5 + 4;
        }

        // ── Skills ──
        if (c.snapshotSkills) {
            y = needsPage(doc, y, 12);
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...DARK);
            doc.text("Skills", 15, y);
            y += 4;
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...MUTED);
            const skillStr = c.snapshotSkills.length > 180 ? c.snapshotSkills.substring(0, 177) + "…" : c.snapshotSkills;
            doc.text(skillStr, 15, y);
            y += 6;
        }

        // ── Work History ──
        const expList: any[] = c.workHistory || [];

        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...DARK);
        doc.text(`Work History  (${expList.length} record${expList.length !== 1 ? "s" : ""})`, 15, y);
        y += 3;

        if (expList.length > 0) {
            const expTableData = expList.map((e: any) => {
                const start = e.start_date
                    ? new Date(e.start_date).toLocaleDateString("en-US", { month: "short", year: "numeric" })
                    : "—";
                const end = e.end_date
                    ? new Date(e.end_date).toLocaleDateString("en-US", { month: "short", year: "numeric" })
                    : "Present";
                const durationMs = e.end_date
                    ? new Date(e.end_date).getTime() - (e.start_date ? new Date(e.start_date).getTime() : 0)
                    : Date.now() - (e.start_date ? new Date(e.start_date).getTime() : Date.now());
                const durationYears = durationMs > 0 ? (durationMs / (1000 * 60 * 60 * 24 * 365)).toFixed(1) : "—";
                const statusLabel = e.isAttested ? "✓ Attested" : "Self-declared";

                return [
                    e.role || "—",
                    e.org || "—",
                    `${start} – ${end}`,
                    `${durationYears} yr`,
                    statusLabel,
                ];
            });

            autoTable(doc, {
                startY: y,
                head: [["Role", "Organization", "Period", "Duration", "Status"]],
                body: expTableData,
                theme: "striped",
                headStyles: { fillColor: SLATE, fontSize: 7.5, textColor: 255 },
                styles: { fontSize: 7.5, cellPadding: 2 },
                columnStyles: {
                    0: { cellWidth: 50 },
                    1: { cellWidth: 48 },
                    2: { cellWidth: 40 },
                    3: { cellWidth: 18 },
                    4: { cellWidth: 23 },
                },
                didParseCell: (data) => {
                    if (data.section === "body" && data.column.index === 4) {
                        const val = data.cell.raw as string;
                        data.cell.styles.textColor = val.startsWith("✓") ? EMERALD : MUTED;
                        data.cell.styles.fontStyle = val.startsWith("✓") ? "bold" : "normal";
                    }
                },
                margin: { left: 15, right: 15 },
            });

            y = (doc as any).lastAutoTable.finalY + 6;
        } else {
            doc.setFontSize(8);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(...MUTED);
            doc.text("No work history recorded at submission time.", 15, y + 4);
            y += 10;
        }

        // ── Attested organisations ──
        if (c.attestedOrgs && c.attestedOrgs.length > 0) {
            y = needsPage(doc, y, 12);
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...DARK);
            doc.text("Attested by organisations:", 15, y);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...EMERALD);
            const orgStr = c.attestedOrgs.join("  ·  ");
            const orgFit = orgStr.length > 170 ? orgStr.substring(0, 167) + "…" : orgStr;
            doc.text(orgFit, 15, y + 5);
            y += 12;
        }

        // ── Recruiter notes ──
        if (c.recruiterNotes) {
            y = needsPage(doc, y, 14);
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...DARK);
            doc.text("Recruiter notes:", 15, y);
            y += 4;
            doc.setFont("helvetica", "italic");
            doc.setTextColor(...MUTED);
            const noteLines = doc.splitTextToSize(c.recruiterNotes, 175);
            doc.text(noteLines.slice(0, 3), 15, y);
            y += Math.min(noteLines.length, 3) * 4.5 + 4;
        }

        // Separator
        y = needsPage(doc, y, 10);
        doc.setDrawColor(...LIGHT);
        doc.setLineWidth(0.3);
        doc.line(15, y, 195, y);
        y += 10;
    });

    // ── Footer on every page ──────────────────────────────────────────────────
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7.5);
        doc.setTextColor(150, 150, 155);
        doc.text(
            "This report is generated from cryptographically verified on-chain data. All proof records are independently attestable.",
            105, 289,
            { align: "center" }
        );
        doc.text(`Page ${i} of ${pageCount}`, 195, 289, { align: "right" });
        doc.text("ChainVolio — Verified Talent Intelligence", 15, 289);
    }

    const fileName = `ChainVolio_Report_${collection.title.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
    doc.save(fileName);
};
