import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generateHiringReport = async (data: { collection: any; candidates: any[] }) => {
    const { collection, candidates } = data;
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString();

    // --- Title Section ---
    doc.setFillColor(18, 18, 21); // Dark background block
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("HIRING INTELLIGENCE REPORT", 105, 20, { align: "center" });
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by ChainVolio Secure • ${dateStr}`, 105, 28, { align: "center" });
    
    doc.setDrawColor(79, 70, 229); // indigo-600
    doc.setLineWidth(1.5);
    doc.line(80, 32, 130, 32);

    // --- Section 1: Executive Summary ---
    let y = 60;
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("1. EXECUTIVE SUMMARY", 15, y);
    
    // Draw divider
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(15, y + 2, 195, y + 2);

    y += 12;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Collection:", 15, y);
    doc.setFont("helvetica", "normal");
    doc.text(collection.title, 55, y);
    
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.text("Target Role:", 15, y);
    doc.setFont("helvetica", "normal");
    doc.text(collection.metadata?.roleType || "Not Specified", 55, y);
    
    y += 8;
    // Stats Grid
    const verifiedCount = candidates.filter(c => c.isVerified).length;
    const avgScoreValue = candidates.reduce((acc, c) => acc + (c.signalScore || 0), 0) / (candidates.length || 1);
    const avgScore = avgScoreValue.toFixed(1);
    const signalDensity = (candidates.reduce((acc, c) => acc + (c.powCount || 0), 0) / (candidates.length || 1)).toFixed(1);
    const networkBreadth = new Set(candidates.flatMap(c => c.attestedOrgs)).size;
    const authorityRateValue = candidates.length ? ((candidates.filter(c => c.attestedCount > 0).length / candidates.length) * 100) : 0;
    const authorityRate = authorityRateValue.toFixed(0);

    const statsData = [
        ["Total Applicants", candidates.length.toString()],
        ["Verified Candidates", verifiedCount.toString()],
        ["Avg. Signal Score", `${avgScore} / 100`],
        ["Authority Rate", `${authorityRate}%`],
        ["Signal Density", `${signalDensity} avg. proofs`],
        ["Network Breadth", `${networkBreadth} partner orgs`]
    ];

    autoTable(doc, {
        startY: y,
        head: [['Metric', 'Value']],
        body: statsData,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229], textColor: 255 },
        styles: { fontSize: 9, cellPadding: 2 },
        margin: { left: 15, right: 15 }
    });

    y = (doc as any).lastAutoTable.finalY + 10;
    
    // Insight Sentences
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(71, 85, 105);
    const insights = [];
    if (verifiedCount === candidates.length && candidates.length > 0) {
        insights.push("All candidates are verified, indicating a high-quality applicant pool.");
    } else if (verifiedCount > 0) {
        insights.push(`${verifiedCount} candidates hold verified status, providing strong baseline trust.`);
    }
    
    if (avgScoreValue > 60) {
        insights.push("Signal strength is above average with strong proof-of-work density.");
    } else if (authorityRateValue > 50) {
        insights.push("High authority rate suggests a high level of third-party attestation across the pool.");
    }
    
    insights.forEach((insight) => {
        doc.text(`• ${insight}`, 15, y);
        y += 6;
    });

    // --- Section 2: Smart Recommendations (Shortlist) ---
    y += 10;
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("2. SMART RECOMMENDATIONS", 15, y);
    doc.line(15, y + 2, 195, y + 2);
    
    const sortedCandidates = [...candidates].sort((a, b) => (b.signalScore || 0) - (a.signalScore || 0));
    const topCandidates = sortedCandidates.slice(0, 5);
    
    const shortlistData = topCandidates.map((c, i) => {
        let decision = "Technical Screening";
        let reason = "Strong volume, requires skills validation.";
        
        if (c.signalScore >= 75 && c.isVerified) {
            decision = "Proceed to Interview";
            reason = "High on-chain credibility and strong attestation backing.";
        } else if (c.signalScore < 30) {
            decision = "Monitor";
            reason = "Limited cryptographically verifiable history.";
        } else if (c.isVerified) {
            decision = "Proceed to Interview";
            reason = "Verified professional standing with confirmed history.";
        } else if (c.powCount > 8) {
            decision = "Technical Screening";
            reason = "Exceptional proof-of-work volume but unverified identity.";
        }
        
        return [
            (i + 1).toString(),
            c.displayName || c.wallet.slice(0, 8),
            c.verificationTier || "None",
            `${c.signalScore}/100`,
            decision,
            reason
        ];
    });

    autoTable(doc, {
        startY: y + 8,
        head: [['Rank', 'Candidate', 'Tier', 'Score', 'Decision', 'Decision Rationale']],
        body: shortlistData,
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] }, // emerald-500
        styles: { fontSize: 8, cellPadding: 3 },
        columnStyles: {
            4: { fontStyle: 'bold' }
        },
        margin: { left: 15, right: 15 }
    });

    // --- Section 3: Signal Analysis ---
    y = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("3. SIGNAL ANALYSIS", 15, y);
    doc.line(15, y + 2, 195, y + 2);
    
    y += 10;
    const highConfidenceCount = candidates.filter(c => (c.signalScore || 0) >= 70).length;
    const avgAttestationRatio = candidates.length ? (candidates.reduce((acc, c) => acc + (c.powCount > 0 ? c.attestedCount / c.powCount : 0), 0) / candidates.length * 100).toFixed(1) : "0.0";
    const topPerformer = sortedCandidates[0];

    const analysisData = [
        ["High Confidence Candidates", highConfidenceCount.toString()],
        ["Avg. Attestation Ratio", `${avgAttestationRatio}%`],
        ["Top Performer", topPerformer?.displayName || topPerformer?.wallet?.slice(0, 8) || "None"]
    ];

    autoTable(doc, {
        startY: y,
        body: analysisData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 60 }
        },
        margin: { left: 15, right: 15 }
    });

    // --- Section 4: Candidate Breakdown ---
    doc.addPage();
    y = 20;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("4. CANDIDATE BREAKDOWN", 15, y);
    doc.line(15, y + 2, 195, y + 2);
    
    const breakdownData = sortedCandidates.map(c => {
        const ratio = c.powCount > 0 ? ((c.attestedCount / c.powCount) * 100).toFixed(0) : "0";
        return [
            c.displayName || "Anonymous",
            c.verificationTier || "unverified",
            c.signalStrength || "Low",
            `Score: ${c.signalScore}/100`,
            `${ratio}%`,
            c.powCount.toString(),
            c.attestedCount.toString(),
        ];
    });

    autoTable(doc, {
        startY: y + 8,
        head: [['Name', 'Reputation Tier', 'Strength', 'Verification Score', 'Attest. Ratio', 'Proofs', 'Attest.']],
        body: breakdownData,
        theme: 'grid',
        headStyles: { fillColor: [51, 65, 85] },
        styles: { fontSize: 7, cellPadding: 2 },
        didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 3) {
                const scoreText = data.cell.raw as string;
                const score = parseInt(scoreText.split(' ')[1]);
                if (score >= 70) data.cell.styles.textColor = [16, 185, 129];
                else if (score >= 30) data.cell.styles.textColor = [217, 119, 6];
            }
            if (data.section === 'body' && data.column.index === 0) {
               data.cell.styles.fontStyle = 'bold';
            }
        },
        margin: { left: 15, right: 15 }
    });

    // --- Section 5: Internal Process Log (Appendix) ---
    y = (doc as any).lastAutoTable.finalY + 15;
    if (y > 250) {
        doc.addPage();
        y = 20;
    }
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("5. INTERNAL PROCESS LOG", 15, y);
    doc.line(15, y + 2, 195, y + 2);
    
    const rawData = sortedCandidates.map(c => [
        c.wallet.slice(0, 8) + "...",
        c.recruiterStatus || "Applied",
        (c.recruiterNotes || "None"),
        new Date(c.submittedAt).toLocaleDateString()
    ]);

    autoTable(doc, {
        startY: y + 8,
        head: [['Wallet Ref', 'Internal Status', 'Recruiter Notes', 'Submission']],
        body: rawData,
        theme: 'plain',
        styles: { fontSize: 7, cellPadding: 1 },
        margin: { left: 15, right: 15 }
    });

    // --- Footer ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        
        // Trust message
        doc.text(
            "This report is generated from cryptographically verified on-chain data. All records are tamper-proof and independently attestable.",
            105,
            285,
            { align: "center" }
        );
        
        // Page number
        doc.text(`Page ${i} of ${pageCount}`, 195, 285, { align: "right" });
    }

    // --- Finalize PDF ---
    const fileName = `ChainVolio_Report_${collection.title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
};
