-- Add card_number to profiles as a sequential number
-- This will automatically assign a number to new profiles
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS card_number INTEGER GENERATED BY DEFAULT AS IDENTITY;

-- Update existing rows based on created_at order
WITH numbered_profiles AS (
  SELECT wallet_address, row_number() OVER (ORDER BY created_at ASC) as rnum
  FROM profiles
)
UPDATE profiles
SET card_number = numbered_profiles.rnum
FROM numbered_profiles
WHERE profiles.wallet_address = numbered_profiles.wallet_address;

-- Reset the identity sequence to start after the last number
SELECT setval(pg_get_serial_sequence('profiles', 'card_number'), (SELECT COALESCE(MAX(card_number), 0) FROM profiles));

-- Add a comment
COMMENT ON COLUMN profiles.card_number IS 'Sequential number based on profile creation order (e.g. 00001)';
